INSERT INTO simplifications (complex_expression,
    simple_alternative) VALUES
    ('At this point in time', 'Now'),
    ('In the event that', 'If'),
    ('Due to the fact that', 'Because'),
    ('With the exception of', 'Except'),
    ('In the near future', 'Soon'),
    ('A large number of', 'Many'),
    ('Prior to the start of', 'Before'),
    ('In order to', 'To'),
    ('As a consequence of', 'Because of'),
    ('Subsequent to', 'After'),
    ('During the course of', 'During'),
    ('With reference to', 'About'),
    ('On a daily basis', 'Daily'),
    ('At an early date', 'Soon'),
    ('For the purpose of', 'For'),
    ('Owing to the fact that', 'Because'),
    ('Come to the realization', 'Realize'),
    ('At all times', 'Always'),
    ('Despite the fact that', 'Although'),
    ('A sufficient amount of', 'Enough'),
    ('Give consideration to', 'Consider'),
    ('In the majority of instances', 'Usually'),
    ('Take into account', 'Consider'),
    ('It is necessary that', 'Must'),
    ('With the aim of', 'To');

-- Verify the data
SELECT * FROM simplifications;
