INSERT INTO one_word_summaries (phrase,
    one_word) VALUES
    ('A strong desire to travel', 'Wanderlust'),
    ('A fear of confined spaces', 'Claustrophobia'),
    ('The ability to understand and share feelings', 'Empathy'),
    ('The art of persuasive speaking or writing', 'Rhetoric'),
    ('A deep love for books', 'Bibliophile'),
    ('A lover of food', 'Gourmet'),
    ('A person who opposes war', 'Pacifist'),
    ('A person who speaks multiple languages', 'Polyglot'),
    ('An expert in the study of ancient human history', 'Archaeologist'),
    ('A selfless concern for others', 'Altruism'),
    ('A period of temporary economic decline', 'Recession'),
    ('The study of human societies and cultures', 'Anthropology'),
    ('A person who loves being alone', 'Introvert'),
    ('A person who thrives in social settings', 'Extrovert'),
    ('A government ruled by a single person with total power', 'Autocracy'),
    ('A government by the people', 'Democracy'),
    ('A place of perfect harmony and happiness', 'Utopia'),
    ('A deep sense of sadness or regret', 'Melancholy'),
    ('The scientific study of celestial objects', 'Astronomy'),
    ('The belief that all things are predetermined', 'Fatalism'),
    ('A person who distrusts humankind', 'Cynic'),
    ('A person who is open to new ideas and experiences', 'Liberal'),
    ('A collection of valuable historical items', 'Archive'),
    ('A sudden realization or insight', 'Epiphany'),
    ('A person who loves and appreciates nature', 'Naturalist');

-- Verify the data
SELECT * FROM one_word_summaries;
