INSERT INTO life_lessons_quotes (quote, author) VALUES
    ('In three words I can sum up everything I’ve learned about life: it goes on.', 'Robert Frost'),
    ('The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.', 'Ralph Waldo Emerson'),
    ('Life is what happens when you’re busy making other plans.', 'John Lennon'),
    ('Good friends, good books, and a sleepy conscience: this is the ideal life.', 'Mark Twain'),
    ('Do not go where the path may lead, go instead where there is no path and leave a trail.', 'Ralph Waldo Emerson'),
    ('To live is the rarest thing in the world. Most people exist, that is all.', 'Oscar Wilde'),
    ('The best way to predict the future is to create it.', 'Abraham Lincoln'),
    ('Life is 10% what happens to us and 90% how we react to it.', 'Charles R. Swindoll'),
    ('Happiness depends upon ourselves.', 'Aristotle'),
    ('Don’t count the days, make the days count.', 'Muhammad Ali'),
    ('Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.', 'Albert Schweitzer'),
    ('In the end, we will remember not the words of our enemies, but the silence of our friends.', 'Martin Luther King Jr.'),
    ('The only impossible journey is the one you never begin.', 'Tony Robbins'),
    ('It does not matter how slowly you go as long as you do not stop.', 'Confucius'),
    ('The only way to do great work is to love what you do.', 'Steve Jobs'),
    ('Your time is limited, so don’t waste it living someone else’s life.', 'Steve Jobs'),
    ('You only live once, but if you do it right, once is enough.', 'Mae West'),
    ('Life isn’t about waiting for the storm to pass, it’s about learning to dance in the rain.', 'Vivian Greene'),
    ('The greatest glory in living lies not in never falling, but in rising every time we fall.', 'Nelson Mandela'),
    ('Life is really simple, but we insist on making it complicated.', 'Confucius'),
    ('Life is short, and it is up to you to make it sweet.', 'Sarah Louise Delany'),
    ('The only limit to our realization of tomorrow is our doubts of today.', 'Franklin D. Roosevelt'),
    ('You miss 100% of the shots you don’t take.', 'Wayne Gretzky'),
    ('Do what you can, with what you have, where you are.', 'Theodore Roosevelt'),
    ('Keep your face always toward the sunshine—and shadows will fall behind you.', 'Walt Whitman'),
    ('Life is either a daring adventure or nothing at all.', 'Helen Keller'),
    ('Act as if what you do makes a difference. It does.', 'William James'),
    ('Don’t wait for the perfect moment, take the moment and make it perfect.', 'Zoey Sayward'),
    ('It’s not the years in your life that count. It’s the life in your years.', 'Abraham Lincoln');
    
-- Verify the data
SELECT * FROM life_lessons_quotes;
