INSERT INTO unique_natural_wonders (wonder, location, fact) VALUES
('Grand Canyon', 'Arizona, USA', 'The Grand Canyon is over 277 miles long and up to 18 miles wide. It was carved by the Colorado River over millions of years.'),
('Great Barrier Reef', 'Queensland, Australia', 'The Great Barrier Reef is the world''s largest coral reef system, home to over 1,500 species of fish.'),
('Aurora Borealis', 'Arctic Region', 'The Aurora Borealis, or Northern Lights, are caused by collisions between electrically charged particles from the sun and Earth''s atmosphere.'),
('Mount Everest', 'Nepal/China', 'Mount Everest is the highest mountain on Earth, standing at 29,032 feet above sea level.'),
('Victoria Falls', 'Zambia/Zimbabwe', 'Victoria Falls is one of the largest and most famous waterfalls in the world, measuring 1,708 meters wide.'),
('Amazon Rainforest', 'South America', 'The Amazon Rainforest is the largest tropical rainforest in the world, home to about 10% of all species on Earth.'),
('Dead Sea', 'Jordan/Israel', 'The Dead Sea is one of the saltiest bodies of water in the world, and is known for its ability to support floating.'),
('Galápagos Islands', 'Ecuador', 'The Galápagos Islands are famous for their unique wildlife and played a significant role in Charles Darwin''s theory of evolution.'),
('Mount Kilimanjaro', 'Tanzania', 'Mount Kilimanjaro is Africa''s highest peak, standing at 19,341 feet and is a dormant volcano.'),
('Bora Bora', 'French Polynesia', 'Bora Bora is famous for its turquoise lagoons and coral reefs, making it a popular honeymoon destination.'),
('Angel Falls', 'Venezuela', 'Angel Falls is the world''s highest uninterrupted waterfall, plunging 3,212 feet from a tabletop mountain.'),
('Salar de Uyuni', 'Bolivia', 'Salar de Uyuni is the largest salt flat in the world, covering over 4,000 square miles.'),
('Great Blue Hole', 'Belize', 'The Great Blue Hole is a giant marine sinkhole that is over 1,000 feet in diameter and 400 feet deep.'),
('Mount Fuji', 'Honshu, Japan', 'Mount Fuji is Japan''s highest and most iconic mountain, standing at 12,388 feet.'),
('Banff National Park', 'Alberta, Canada', 'Banff National Park is Canada''s first national park, known for its stunning mountains, lakes, and wildlife.'),
('Iguaçu Falls', 'Brazil/Argentina', 'Iguaçu Falls consists of 275 individual falls and is one of the largest waterfall systems in the world.'),
('Crater Lake', 'Oregon, USA', 'Crater Lake is the deepest lake in the United States and was formed by a collapsed volcano.'),
('Yellowstone National Park', 'Wyoming, Montana, and Idaho, USA', 'Yellowstone is the world''s first national park, famous for its geothermal features like Old Faithful geyser.'),
('Patagonia', 'Argentina/Chile', 'Patagonia is known for its rugged terrain, glaciers, and unique wildlife, and is a popular destination for hiking and adventure.'),
('Mount Vesuvius', 'Naples, Italy', 'Mount Vesuvius is the most famous volcano in Europe, known for its eruption in AD 79 that destroyed Pompeii.'),
('Niagara Falls', 'USA/Canada', 'Niagara Falls is a group of three waterfalls on the border between Canada and the United States, attracting millions of visitors each year.'),
('Table Mountain', 'Cape Town, South Africa', 'Table Mountain is known for its flat-topped summit, offering panoramic views of Cape Town and the surrounding areas.'),
('Zhangjiajie National Forest Park', 'Hunan, China', 'Zhangjiajie is famous for its towering sandstone pillars, which inspired the floating mountains in the movie Avatar.'),
('Mount Roraima', 'Venezuela/Brazil/Guyana', 'Mount Roraima is a tabletop mountain, which inspired the setting for Sir Arthur Conan Doyle''s novel "The Lost World."'),
('Fossilized Forest', 'North Dakota, USA', 'The Fossilized Forest is a site where ancient tree stumps have been preserved and turned into stone over millions of years.'),
('Lake Baikal', 'Siberia, Russia', 'Lake Baikal is the deepest and oldest freshwater lake in the world, containing about 20% of the world''s unfrozen surface water.'),
('Kakadu National Park', 'Northern Territory, Australia', 'Kakadu National Park is a UNESCO World Heritage site, known for its rich biodiversity and ancient rock art.'),
('Mount Aoraki', 'South Island, New Zealand', 'Mount Aoraki is the highest mountain in New Zealand, part of the Southern Alps range.'),
('Lake Titicaca', 'Bolivia/Peru', 'Lake Titicaca is the largest lake in South America by volume of water and surface area, and is considered sacred by the indigenous people.'),
('The Door to Hell', 'Turkmenistan', 'The Door to Hell is a natural gas field that has been burning continuously since it was set on fire in 1971.');

-- Verify the data
SELECT * FROM unique_natural_wonders;