INSERT INTO birthday_celebration_quotes (quote, author) VALUES
    ('Count your life by smiles, not tears. Count your age by friends, not years. Happy birthday!', 'John Lennon'),
    ('The more you praise and celebrate your life, the more there is in life to celebrate. Happy Birthday!', 'Oprah Winfrey'),
    ('Wishing you a day filled with love and joy. Happy Birthday!', 'Unknown'),
    ('Your birthday is the first day of another 365-day journey around the sun. Enjoy the ride!', 'Unknown'),
    ('Cheers to you and your accomplishments, and here’s to many more years of success. Happy Birthday!', 'Unknown'),
    ('A birthday is just the first day of another 365-day journey around the sun. Enjoy the trip!', 'Unknown'),
    ('Let us never know what old age is. Let us know the happiness time brings, not the end of it. Happy birthday!', 'Unknown'),
    ('Age is an issue of mind over matter. If you don’t mind, it doesn’t matter. Happy birthday!', 'Unknown'),
    ('You are never too old to set another goal or to dream a new dream. Happy birthday!', 'C.S. Lewis'),
    ('The older you get, the better you get, unless you are a banana. Happy birthday!', 'Unknown'),
    ('You are the brightest star in my life, and I am so grateful to have you. Happy birthday!', 'Unknown'),
    ('Birthdays are nature’s way of telling us to eat more cake. Happy birthday!', 'Unknown'),
    ('Life should not only be lived, it should be celebrated. Happy birthday!', 'Osho'),
    ('May your birthday be filled with laughter, joy, and all the love you deserve. Happy Birthday!', 'Unknown'),
    ('You’re not getting older, you’re getting better. Happy birthday!', 'Unknown'),
    ('Birthdays are the universe’s way of telling us to eat more cake. Enjoy the day!', 'Unknown'),
    ('Happy birthday to the one who makes my world brighter every day. You are amazing!', 'Unknown'),
    ('May your birthday be the start of a year filled with happiness, love, and success. Enjoy the day!', 'Unknown'),
    ('On your birthday, may the next 12 months be full of joy, health, and countless blessings. Happy Birthday!', 'Unknown'),
    ('Age is merely the number of years the world has been enjoying you. Cheers to you and your achievements. Happy birthday!', 'Unknown'),
    ('May your birthday be full of beautiful moments and memories that last a lifetime. Happy Birthday!', 'Unknown'),
    ('Wishing you endless happiness, love, and success as you celebrate your special day. Happy birthday!', 'Unknown'),
    ('May your birthday be filled with laughter, joy, and all your heart’s desires. Happy Birthday!', 'Unknown'),
    ('Life is a journey and birthdays are a way of celebrating the adventures you’ve had. Happy birthday!', 'Unknown'),
    ('Enjoy the little things in life, for one day you may look back and realize they were the big things. Happy Birthday!', 'Unknown'),
    ('May your birthday be the beginning of a wonderful year full of blessings. Happy birthday!', 'Unknown'),
    ('Wishing you a birthday as amazing as you are. Enjoy every moment!', 'Unknown'),
    ('On your special day, I wish you good health, love, and happiness. Happy birthday!', 'Unknown'),
    ('May your day be filled with laughter, joy, and memories that last a lifetime. Happy Birthday!', 'Unknown');
    
-- Verify the data
SELECT * FROM birthday_celebration_quotes;
