INSERT INTO humorous_proverbs (proverb, meaning) VALUES
    ('Laughter is the best medicine.', 'Laughter can be healing and is good for your health.'),
    ('Don’t count your chickens before they hatch.', 'Don’t assume things will turn out the way you want them to before they actually do.'),
    ('A penny saved is a penny earned.', 'Saving money is just as valuable as earning it.'),
    ('You can’t have your cake and eat it too.', 'You can’t have two conflicting things at the same time.'),
    ('The early bird gets the worm.', 'The person who takes action early gets the advantage.'),
    ('A watched pot never boils.', 'If you wait impatiently for something to happen, it will feel like it takes longer.'),
    ('Actions speak louder than words.', 'What people do is more important than what they say.'),
    ('Don’t cry over spilled milk.', 'Don’t be upset over something that can’t be undone.'),
    ('When the cat’s away, the mice will play.', 'People will take advantage of the absence of authority.'),
    ('You can lead a horse to water, but you can’t make it drink.', 'You can offer help, but you can’t force someone to accept it.'),
    ('The grass is always greener on the other side.', 'People often think others have it better, but they don’t.'),
    ('The squeaky wheel gets the grease.', 'The person who complains the most gets the attention they want.'),
    ('Too many cooks spoil the broth.', 'Too many people involved in a task can ruin it.'),
    ('Don’t bite the hand that feeds you.', 'Don’t harm or criticize those who help you.'),
    ('You can’t teach an old dog new tricks.', 'It’s hard to teach someone new skills if they’ve done things a certain way for a long time.'),
    ('It’s always darkest before the dawn.', 'Things often seem worse before they improve.'),
    ('There’s no place like home.', 'Home is the most comfortable and familiar place.'),
    ('What’s good for the goose is good for the gander.', 'What is good for one person should also be good for others in similar circumstances.'),
    ('Let sleeping dogs lie.', 'Don’t stir up problems that are better left alone.'),
    ('Make hay while the sun shines.', 'Take advantage of good opportunities while they last.'),
    ('You can’t make an omelet without breaking a few eggs.', 'You must make sacrifices to achieve something.'),
    ('People who live in glass houses shouldn’t throw stones.', 'Don’t criticize others if you have similar flaws.'),
    ('The proof of the pudding is in the eating.', 'The true value of something can only be judged when it is put to use.'),
    ('If you can’t beat them, join them.', 'If you can’t oppose something, then you might as well participate in it.'),
    ('Don’t put all your eggs in one basket.', 'Don’t risk everything on a single opportunity or plan.'),
    ('There’s no such thing as a free lunch.', 'Everything has a cost, even if it’s not immediately apparent.'),
    ('You can’t please everyone.', 'It’s impossible to make everyone happy, so don’t try.'),
    ('Where there’s smoke, there’s fire.', 'Rumors or signs of something often indicate that there is truth to it.');

-- Verify the data
SELECT * FROM humorous_proverbs;
